# charts/vault/values.yaml - Configuraci贸n para instalar Vault con Helm

# Configuraci贸n del modo de Vault
server:
  dev:
    enabled: true  # Usar modo Dev para simplicidad
  ha:
    enabled: false

# Habilitar el Vault Agent Injector
injector:
  enabled: true

# Configuraci贸n de la autenticaci贸n Kubernetes
authMethods:
  kubernetes:
    enabled: true
    path: kubernetes
    kubernetesHost: "http://kubernetes.default.svc"
