# application.yml - Configuración de Spring Boot para conectarse a S3

spring:
  cloud:
    vault:
      uri: http://vault:8200
      authentication: KUBERNETES
      kubernetes:
        role: springboot-vault-s3
        service-account-token-file: /var/run/secrets/kubernetes.io/serviceaccount/token
        ca-cert-file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      application-name: springboot-vault-s3

aws:
  accessKey: ${S3_ACCESS_KEY}
  secretKey: ${S3_SECRET_KEY}
