# secrets.yaml - Creación de secretos en Vault para acceder a Amazon S3

apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
type: Opaque
data:
  access_key: c29tZWFwaS1hY2Nlc3MtZXhhbXBsZQ==  # Codificado en base64
  secret_key: c29tZWFwaS1zZWNyZXQtZXhhbXBsZQ==  # Codificado en base64
